---
title: My awesome site
timezone: UTC
collections:
  cluster:
    title: Cluster
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  services:
    title: services
    output: true
email: m.besnard95@gmail.com
description: This is my awesome website. Enjoy !
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
